# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField(default=-1)),
                ('room_name', models.CharField(default='room', max_length=30)),
                ('owner_id', models.IntegerField(default=-1)),
                ('player_num', models.IntegerField(default=0)),
                ('player_id', models.CharField(default=b'-1', max_length=100)),
                ('player_nick', models.CharField(default='nick', max_length=300)),
                ('player_role', models.CharField(default='village', max_length=200)),
                ('player_alive', models.CharField(default='true', max_length=100)),
                ('sheriff_id', models.IntegerField(default=-1)),
                ('round', models.IntegerField(default=0)),
                ('state', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='standings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=-1)),
                ('role', models.CharField(default='village', max_length=10)),
                ('result', models.BooleanField(default=False)),
                ('id_list', models.CharField(default=b'-1', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='name',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='introduce',
            field=models.CharField(default='\u65e0\u53ef\u5949\u544a', max_length=200),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='nick_name',
            field=models.CharField(default='nick', max_length=30),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_name',
            field=models.CharField(default='user', max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(default='123456', max_length=30),
        ),
    ]
